name: Lighthouse

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: lighthouse-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: pnpm/action-setup@a7487c7e89a18be500035ba77b504471abd873dd # v4.1.0
        with:
          version: 9.15.0

      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Build
        env:
          SITE_URL: https://yoavsb25.github.io
          NEXT_PUBLIC_GITHUB_USERNAME: Yoavsb25
        run: pnpm build

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@2f8dda67ae9cbd95623f973ee5998335b007ce5e # v12.1.0
        with:
          configPath: ./.lighthouserc.json
          uploadArtifacts: true
          temporaryPublicStorage: true
